build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
    tests:
      environment:
        variables:
          TEST_TCP_TRANSPORT_URL: 'tcp://localhost:4000'
      services:
        jsonrpc:
          image: strider2038/json-rpc-mock-server
          ports:
            - 4000
      tests:
        override:
          - composer check
          - command: ./vendor/bin/phpunit --coverage-clover clover.xml
            coverage:
              file: clover.xml
              format: 'php-clover'

filter:
  excluded_paths:
    - 'tests/*'
checks:
  php: true
coding_style:
  php: {  }
